[2023-08-31 13:23:33,787] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task 2022-01-13T00:00:00+00:00 [queued]>
[2023-08-31 13:23:33,832] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task 2022-01-13T00:00:00+00:00 [queued]>
[2023-08-31 13:23:33,832] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-08-31 13:23:33,833] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-08-31 13:23:33,833] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-08-31 13:23:33,856] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): second_task> on 2022-01-13T00:00:00+00:00
[2023-08-31 13:23:33,861] {standard_task_runner.py:52} INFO - Started process 5519 to run task
[2023-08-31 13:23:33,895] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag_v5', 'second_task', '2022-01-13T00:00:00+00:00', '--job-id', '508', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpxtdusn60', '--error-file', '/tmp/tmp53v1xd5q']
[2023-08-31 13:23:33,912] {standard_task_runner.py:77} INFO - Job 508: Subtask second_task
[2023-08-31 13:23:34,060] {logging_mixin.py:104} INFO - Running <TaskInstance: our_first_dag_v5.second_task 2022-01-13T00:00:00+00:00 [running]> on host e7718740c1e6
[2023-08-31 13:23:34,229] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=devendra
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-13T00:00:00+00:00
[2023-08-31 13:23:34,230] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-08-31 13:23:34,232] {bash.py:158} INFO - Running command: echo hey, I am task2 and will be running after task1!
[2023-08-31 13:23:34,274] {bash.py:169} INFO - Output:
[2023-08-31 13:23:34,345] {bash.py:173} INFO - hey, I am task2 and will be running after task1!
[2023-08-31 13:23:34,368] {bash.py:177} INFO - Command exited with return code 0
[2023-08-31 13:23:34,439] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20220113T000000, start_date=20230831T132333, end_date=20230831T132334
[2023-08-31 13:23:34,861] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-31 13:23:34,906] {local_task_job.py:146} INFO - Task exited with return code 0
